/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-wave': 'linear-gradient(to top, #d1acee 0%, #fff 100%)'
      },
      animation: {
        'button-hover': 'button-gradient 3s linear infinite',
        'wave': 'wave 15s linear infinite',
        'background-gradient': 'background-gradient 1s linear infinite',
      },
      keyframes: {
        'button-gradient': {
          '0%': { transform: 'scaleX(1) scaleY(1) rotate(0deg)' },
          '50%': { transform: 'scaleX(0) scaleY(1) rotate(180deg)' },
          '100%': { transform: 'scaleX(1) scaleY(1) rotate(360deg)' },
        },
        'wave': {
          'from': { transform: 'rotate(0deg)'},
          'to': { transform: 'rotate(360deg)'},
        },
        'background-gradient': {
          // '0%': {
          //   backgroundImage: 'conic-gradient(from 0deg at 50% 50%, var(--tw-gradient-stops))'
          // },
          // '50%': {
          //   backgroundImage: 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))'
          // },
          // '100%': {
          //   backgroundImage: 'conic-gradient(from 0deg at 50% 50%, var(--tw-gradient-stops))'
          // },
            "0%": {backgroundImage: 'conic-gradient(from 0deg at 50% 50%, var(--tw-gradient-stops))'},
            "1%": {backgroundImage: 'conic-gradient(from 1deg at 50% 50%, var(--tw-gradient-stops))'},
            "2%": {backgroundImage: 'conic-gradient(from 2deg at 50% 50%, var(--tw-gradient-stops))'},
            "3%": {backgroundImage: 'conic-gradient(from 3deg at 50% 50%, var(--tw-gradient-stops))'},
            "4%": {backgroundImage: 'conic-gradient(from 4deg at 50% 50%, var(--tw-gradient-stops))'},
            "5%": {backgroundImage: 'conic-gradient(from 5deg at 50% 50%, var(--tw-gradient-stops))'},
            "6%": {backgroundImage: 'conic-gradient(from 6deg at 50% 50%, var(--tw-gradient-stops))'},
            "7%": {backgroundImage: 'conic-gradient(from 7deg at 50% 50%, var(--tw-gradient-stops))'},
            "8%": {backgroundImage: 'conic-gradient(from 8deg at 50% 50%, var(--tw-gradient-stops))'},
            "9%": {backgroundImage: 'conic-gradient(from 9deg at 50% 50%, var(--tw-gradient-stops))'},
            "10%": {backgroundImage: 'conic-gradient(from 10deg at 50% 50%, var(--tw-gradient-stops))'},
            "11%": {backgroundImage: 'conic-gradient(from 11deg at 50% 50%, var(--tw-gradient-stops))'},
            "12%": {backgroundImage: 'conic-gradient(from 12deg at 50% 50%, var(--tw-gradient-stops))'},
            "13%": {backgroundImage: 'conic-gradient(from 13deg at 50% 50%, var(--tw-gradient-stops))'},
            "14%": {backgroundImage: 'conic-gradient(from 14deg at 50% 50%, var(--tw-gradient-stops))'},
            "15%": {backgroundImage: 'conic-gradient(from 15deg at 50% 50%, var(--tw-gradient-stops))'},
            "16%": {backgroundImage: 'conic-gradient(from 16deg at 50% 50%, var(--tw-gradient-stops))'},
            "17%": {backgroundImage: 'conic-gradient(from 17deg at 50% 50%, var(--tw-gradient-stops))'},
            "18%": {backgroundImage: 'conic-gradient(from 18deg at 50% 50%, var(--tw-gradient-stops))'},
            "19%": {backgroundImage: 'conic-gradient(from 19deg at 50% 50%, var(--tw-gradient-stops))'},
            "20%": {backgroundImage: 'conic-gradient(from 20deg at 50% 50%, var(--tw-gradient-stops))'},
            "21%": {backgroundImage: 'conic-gradient(from 21deg at 50% 50%, var(--tw-gradient-stops))'},
            "22%": {backgroundImage: 'conic-gradient(from 22deg at 50% 50%, var(--tw-gradient-stops))'},
            "23%": {backgroundImage: 'conic-gradient(from 23deg at 50% 50%, var(--tw-gradient-stops))'},
            "24%": {backgroundImage: 'conic-gradient(from 24deg at 50% 50%, var(--tw-gradient-stops))'},
            "25%": {backgroundImage: 'conic-gradient(from 25deg at 50% 50%, var(--tw-gradient-stops))'},
            "26%": {backgroundImage: 'conic-gradient(from 26deg at 50% 50%, var(--tw-gradient-stops))'},
            "27%": {backgroundImage: 'conic-gradient(from 27deg at 50% 50%, var(--tw-gradient-stops))'},
            "28%": {backgroundImage: 'conic-gradient(from 28deg at 50% 50%, var(--tw-gradient-stops))'},
            "29%": {backgroundImage: 'conic-gradient(from 29deg at 50% 50%, var(--tw-gradient-stops))'},
            "30%": {backgroundImage: 'conic-gradient(from 30deg at 50% 50%, var(--tw-gradient-stops))'},
            "31%": {backgroundImage: 'conic-gradient(from 31deg at 50% 50%, var(--tw-gradient-stops))'},
            "32%": {backgroundImage: 'conic-gradient(from 32deg at 50% 50%, var(--tw-gradient-stops))'},
            "33%": {backgroundImage: 'conic-gradient(from 33deg at 50% 50%, var(--tw-gradient-stops))'},
            "34%": {backgroundImage: 'conic-gradient(from 34deg at 50% 50%, var(--tw-gradient-stops))'},
            "35%": {backgroundImage: 'conic-gradient(from 35deg at 50% 50%, var(--tw-gradient-stops))'},
            "36%": {backgroundImage: 'conic-gradient(from 36deg at 50% 50%, var(--tw-gradient-stops))'},
            "37%": {backgroundImage: 'conic-gradient(from 37deg at 50% 50%, var(--tw-gradient-stops))'},
            "38%": {backgroundImage: 'conic-gradient(from 38deg at 50% 50%, var(--tw-gradient-stops))'},
            "39%": {backgroundImage: 'conic-gradient(from 39deg at 50% 50%, var(--tw-gradient-stops))'},
            "40%": {backgroundImage: 'conic-gradient(from 40deg at 50% 50%, var(--tw-gradient-stops))'},
            "41%": {backgroundImage: 'conic-gradient(from 41deg at 50% 50%, var(--tw-gradient-stops))'},
            "42%": {backgroundImage: 'conic-gradient(from 42deg at 50% 50%, var(--tw-gradient-stops))'},
            "43%": {backgroundImage: 'conic-gradient(from 43deg at 50% 50%, var(--tw-gradient-stops))'},
            "44%": {backgroundImage: 'conic-gradient(from 44deg at 50% 50%, var(--tw-gradient-stops))'},
            "45%": {backgroundImage: 'conic-gradient(from 45deg at 50% 50%, var(--tw-gradient-stops))'},
            "46%": {backgroundImage: 'conic-gradient(from 46deg at 50% 50%, var(--tw-gradient-stops))'},
            "47%": {backgroundImage: 'conic-gradient(from 47deg at 50% 50%, var(--tw-gradient-stops))'},
            "48%": {backgroundImage: 'conic-gradient(from 48deg at 50% 50%, var(--tw-gradient-stops))'},
            "49%": {backgroundImage: 'conic-gradient(from 49deg at 50% 50%, var(--tw-gradient-stops))'},
            "50%": {backgroundImage: 'conic-gradient(from 50deg at 50% 50%, var(--tw-gradient-stops))'},
            "51%": {backgroundImage: 'conic-gradient(from 51deg at 50% 50%, var(--tw-gradient-stops))'},
            "52%": {backgroundImage: 'conic-gradient(from 52deg at 50% 50%, var(--tw-gradient-stops))'},
            "53%": {backgroundImage: 'conic-gradient(from 53deg at 50% 50%, var(--tw-gradient-stops))'},
            "54%": {backgroundImage: 'conic-gradient(from 54deg at 50% 50%, var(--tw-gradient-stops))'},
            "55%": {backgroundImage: 'conic-gradient(from 55deg at 50% 50%, var(--tw-gradient-stops))'},
            "56%": {backgroundImage: 'conic-gradient(from 56deg at 50% 50%, var(--tw-gradient-stops))'},
            "57%": {backgroundImage: 'conic-gradient(from 57deg at 50% 50%, var(--tw-gradient-stops))'},
            "58%": {backgroundImage: 'conic-gradient(from 58deg at 50% 50%, var(--tw-gradient-stops))'},
            "59%": {backgroundImage: 'conic-gradient(from 59deg at 50% 50%, var(--tw-gradient-stops))'},
            "60%": {backgroundImage: 'conic-gradient(from 60deg at 50% 50%, var(--tw-gradient-stops))'},
            "61%": {backgroundImage: 'conic-gradient(from 61deg at 50% 50%, var(--tw-gradient-stops))'},
            "62%": {backgroundImage: 'conic-gradient(from 62deg at 50% 50%, var(--tw-gradient-stops))'},
            "63%": {backgroundImage: 'conic-gradient(from 63deg at 50% 50%, var(--tw-gradient-stops))'},
            "64%": {backgroundImage: 'conic-gradient(from 64deg at 50% 50%, var(--tw-gradient-stops))'},
            "65%": {backgroundImage: 'conic-gradient(from 65deg at 50% 50%, var(--tw-gradient-stops))'},
            "66%": {backgroundImage: 'conic-gradient(from 66deg at 50% 50%, var(--tw-gradient-stops))'},
            "67%": {backgroundImage: 'conic-gradient(from 67deg at 50% 50%, var(--tw-gradient-stops))'},
            "68%": {backgroundImage: 'conic-gradient(from 68deg at 50% 50%, var(--tw-gradient-stops))'},
            "69%": {backgroundImage: 'conic-gradient(from 69deg at 50% 50%, var(--tw-gradient-stops))'},
            "70%": {backgroundImage: 'conic-gradient(from 70deg at 50% 50%, var(--tw-gradient-stops))'},
            "71%": {backgroundImage: 'conic-gradient(from 71deg at 50% 50%, var(--tw-gradient-stops))'},
            "72%": {backgroundImage: 'conic-gradient(from 72deg at 50% 50%, var(--tw-gradient-stops))'},
            "73%": {backgroundImage: 'conic-gradient(from 73deg at 50% 50%, var(--tw-gradient-stops))'},
            "74%": {backgroundImage: 'conic-gradient(from 74deg at 50% 50%, var(--tw-gradient-stops))'},
            "75%": {backgroundImage: 'conic-gradient(from 75deg at 50% 50%, var(--tw-gradient-stops))'},
            "76%": {backgroundImage: 'conic-gradient(from 76deg at 50% 50%, var(--tw-gradient-stops))'},
            "77%": {backgroundImage: 'conic-gradient(from 77deg at 50% 50%, var(--tw-gradient-stops))'},
            "78%": {backgroundImage: 'conic-gradient(from 78deg at 50% 50%, var(--tw-gradient-stops))'},
            "79%": {backgroundImage: 'conic-gradient(from 79deg at 50% 50%, var(--tw-gradient-stops))'},
            "80%": {backgroundImage: 'conic-gradient(from 80deg at 50% 50%, var(--tw-gradient-stops))'},
            "81%": {backgroundImage: 'conic-gradient(from 81deg at 50% 50%, var(--tw-gradient-stops))'},
            "82%": {backgroundImage: 'conic-gradient(from 82deg at 50% 50%, var(--tw-gradient-stops))'},
            "83%": {backgroundImage: 'conic-gradient(from 83deg at 50% 50%, var(--tw-gradient-stops))'},
            "84%": {backgroundImage: 'conic-gradient(from 84deg at 50% 50%, var(--tw-gradient-stops))'},
            "85%": {backgroundImage: 'conic-gradient(from 85deg at 50% 50%, var(--tw-gradient-stops))'},
            "86%": {backgroundImage: 'conic-gradient(from 86deg at 50% 50%, var(--tw-gradient-stops))'},
            "87%": {backgroundImage: 'conic-gradient(from 87deg at 50% 50%, var(--tw-gradient-stops))'},
            "88%": {backgroundImage: 'conic-gradient(from 88deg at 50% 50%, var(--tw-gradient-stops))'},
            "89%": {backgroundImage: 'conic-gradient(from 89deg at 50% 50%, var(--tw-gradient-stops))'},
            "90%": {backgroundImage: 'conic-gradient(from 90deg at 50% 50%, var(--tw-gradient-stops))'},
            "91%": {backgroundImage: 'conic-gradient(from 91deg at 50% 50%, var(--tw-gradient-stops))'},
            "92%": {backgroundImage: 'conic-gradient(from 92deg at 50% 50%, var(--tw-gradient-stops))'},
            "93%": {backgroundImage: 'conic-gradient(from 93deg at 50% 50%, var(--tw-gradient-stops))'},
            "94%": {backgroundImage: 'conic-gradient(from 94deg at 50% 50%, var(--tw-gradient-stops))'},
            "95%": {backgroundImage: 'conic-gradient(from 95deg at 50% 50%, var(--tw-gradient-stops))'},
            "96%": {backgroundImage: 'conic-gradient(from 96deg at 50% 50%, var(--tw-gradient-stops))'},
            "97%": {backgroundImage: 'conic-gradient(from 97deg at 50% 50%, var(--tw-gradient-stops))'},
            "98%": {backgroundImage: 'conic-gradient(from 98deg at 50% 50%, var(--tw-gradient-stops))'},
            "99%": {backgroundImage: 'conic-gradient(from 99deg at 50% 50%, var(--tw-gradient-stops))'},
            "100%": {backgroundImage: 'conic-gradient(from 100deg at 50% 50%, var(--tw-gradient-stops))'},
        }
      },
      backgroundSize: {
        'size-200': '200% 200%',
      },
      backgroundPosition: {
        'pos-0': '0% 0%',
        'pos-100': '100% 100%',
      },
    },
  },
  plugins: [],
}
